var namespace_tobii_1_1_eye_tracking =
[
    [ "Stubs", "d7/ded/namespace_tobii_1_1_eye_tracking_1_1_stubs.html", "d7/ded/namespace_tobii_1_1_eye_tracking_1_1_stubs" ],
    [ "EyePositions", "d4/de5/class_tobii_1_1_eye_tracking_1_1_eye_positions.html", "d4/de5/class_tobii_1_1_eye_tracking_1_1_eye_positions" ],
    [ "EyeTrackingHost", "df/d1e/class_tobii_1_1_eye_tracking_1_1_eye_tracking_host.html", null ],
    [ "EyeTrackingHostStub", "de/dd2/class_tobii_1_1_eye_tracking_1_1_eye_tracking_host_stub.html", "de/dd2/class_tobii_1_1_eye_tracking_1_1_eye_tracking_host_stub" ],
    [ "EyeTrackingSettingsWindow", "d0/d3e/class_tobii_1_1_eye_tracking_1_1_eye_tracking_settings_window.html", null ],
    [ "FixationPoint", "d3/d61/class_tobii_1_1_eye_tracking_1_1_fixation_point.html", "d3/d61/class_tobii_1_1_eye_tracking_1_1_fixation_point" ],
    [ "FocusedObject", "d4/d38/struct_tobii_1_1_eye_tracking_1_1_focused_object.html", "d4/d38/struct_tobii_1_1_eye_tracking_1_1_focused_object" ],
    [ "GameViewInfo", "d5/d7c/struct_tobii_1_1_eye_tracking_1_1_game_view_info.html", "d5/d7c/struct_tobii_1_1_eye_tracking_1_1_game_view_info" ],
    [ "GazeAware", "dd/ddc/class_tobii_1_1_eye_tracking_1_1_gaze_aware.html", "dd/ddc/class_tobii_1_1_eye_tracking_1_1_gaze_aware" ],
    [ "GazeFocus", "d4/dd8/class_tobii_1_1_eye_tracking_1_1_gaze_focus.html", null ],
    [ "GazeFocusSettings", "d6/dd3/struct_tobii_1_1_eye_tracking_1_1_gaze_focus_settings.html", "d6/dd3/struct_tobii_1_1_eye_tracking_1_1_gaze_focus_settings" ],
    [ "GazeFocusStub", "df/d91/class_tobii_1_1_eye_tracking_1_1_gaze_focus_stub.html", "df/d91/class_tobii_1_1_eye_tracking_1_1_gaze_focus_stub" ],
    [ "GazePoint", "d1/d7a/class_tobii_1_1_eye_tracking_1_1_gaze_point.html", "d1/d7a/class_tobii_1_1_eye_tracking_1_1_gaze_point" ],
    [ "GazeTracking", "d0/d50/class_tobii_1_1_eye_tracking_1_1_gaze_tracking.html", "d0/d50/class_tobii_1_1_eye_tracking_1_1_gaze_tracking" ],
    [ "HitTestFromPoint", "dd/d6b/class_tobii_1_1_eye_tracking_1_1_hit_test_from_point.html", null ],
    [ "IDataProvider", "d0/d04/interface_tobii_1_1_eye_tracking_1_1_i_data_provider.html", "d0/d04/interface_tobii_1_1_eye_tracking_1_1_i_data_provider" ],
    [ "IEyeTrackingHost", "da/dfe/interface_tobii_1_1_eye_tracking_1_1_i_eye_tracking_host.html", "da/dfe/interface_tobii_1_1_eye_tracking_1_1_i_eye_tracking_host" ],
    [ "IGazeFocus", "d4/db2/interface_tobii_1_1_eye_tracking_1_1_i_gaze_focus.html", "d4/db2/interface_tobii_1_1_eye_tracking_1_1_i_gaze_focus" ],
    [ "IGazeFocusable", "dc/d2b/interface_tobii_1_1_eye_tracking_1_1_i_gaze_focusable.html", "dc/d2b/interface_tobii_1_1_eye_tracking_1_1_i_gaze_focusable" ],
    [ "IRegisterGazeFocusable", "d4/dbd/interface_tobii_1_1_eye_tracking_1_1_i_register_gaze_focusable.html", "d4/dbd/interface_tobii_1_1_eye_tracking_1_1_i_register_gaze_focusable" ],
    [ "IScorer", "d6/d58/interface_tobii_1_1_eye_tracking_1_1_i_scorer.html", "d6/d58/interface_tobii_1_1_eye_tracking_1_1_i_scorer" ],
    [ "IStateValue", "d0/d0a/interface_tobii_1_1_eye_tracking_1_1_i_state_value.html", "d0/d0a/interface_tobii_1_1_eye_tracking_1_1_i_state_value" ],
    [ "ITimestamped", "de/d69/interface_tobii_1_1_eye_tracking_1_1_i_timestamped.html", "de/d69/interface_tobii_1_1_eye_tracking_1_1_i_timestamped" ],
    [ "MultiRaycastHistoricHitScore", "d7/d75/class_tobii_1_1_eye_tracking_1_1_multi_raycast_historic_hit_score.html", "d7/d75/class_tobii_1_1_eye_tracking_1_1_multi_raycast_historic_hit_score" ],
    [ "ScoredObject", "d7/d0a/class_tobii_1_1_eye_tracking_1_1_scored_object.html", "d7/d0a/class_tobii_1_1_eye_tracking_1_1_scored_object" ],
    [ "SingleEyePosition", "dd/d4e/class_tobii_1_1_eye_tracking_1_1_single_eye_position.html", "dd/d4e/class_tobii_1_1_eye_tracking_1_1_single_eye_position" ],
    [ "SingleRaycastHistoricHitScore", "d1/d45/class_tobii_1_1_eye_tracking_1_1_single_raycast_historic_hit_score.html", "d1/d45/class_tobii_1_1_eye_tracking_1_1_single_raycast_historic_hit_score" ],
    [ "SingleRayCastNoScore", "d8/d3f/class_tobii_1_1_eye_tracking_1_1_single_ray_cast_no_score.html", "d8/d3f/class_tobii_1_1_eye_tracking_1_1_single_ray_cast_no_score" ],
    [ "StateValue", "d7/d15/class_tobii_1_1_eye_tracking_1_1_state_value.html", "d7/d15/class_tobii_1_1_eye_tracking_1_1_state_value" ],
    [ "StateValueStub", "dd/dfd/class_tobii_1_1_eye_tracking_1_1_state_value_stub.html", "dd/dfd/class_tobii_1_1_eye_tracking_1_1_state_value_stub" ],
    [ "UserPresence", "d5/d1c/class_tobii_1_1_eye_tracking_1_1_user_presence.html", "d5/d1c/class_tobii_1_1_eye_tracking_1_1_user_presence" ]
];